server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: horasextras-service
          uri: lb://horasextras-service
          predicates:
            - Path=/horasExtras/**
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleado/**
        - id: justificativos-service
          uri: lb://justificativos-service
          predicates:
            - Path=/justificativo/**
        - id: planillasueldo-service
          uri: lb://planillasueldo-service
          predicates:
            - Path=/calculoPlanillas/**
        - id: marcasreloj-service
          uri: lb://marcasreloj-service
          predicates:
            - Path=/marcasReloj/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

# server:
#   port: 8082
  
# eureka:
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       default-zone: http://localhost:8761/eureka
#   instance:
#     hostname: localhost

# spring:
#   cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true
#       default-filters:
#         - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#       globalcors:
#         cors-configurations:
#           '[/**]':
#             allowed-origin-patterns: '*'
#             allowed-methods: "*"
#             allowed-headers: "*"
#             allow-credentials: true          
#       routes:
#         - id: autorizacion-service
#           uri: lb://autorizacion-service
#           predicates:
#             - Path=/autorizacion/**
#         - id: empleado-service
#           uri: lb://empleado-service
#           predicates:
#             - Path=/empleado/**
#         - id: justificacion-service
#           uri: lb://justificacion-service
#           predicates:
#             - Path=/justificacion/**
#         - id: planilla-service
#           uri: lb://planilla-service
#           predicates:
#             - Path=/planilla/**        
#         - id: reloj-service
#           uri: lb://reloj-service
#           predicates:
#             - Path=/reloj/**